package aucta.dev.mercator_core.enums;

public enum CategoryType {
    HOME_AND_KITCHEN,
    WOMENS_CLOTHING,
    WOMENS_SHOES,
    WOMENS_LINGERIE_AND_LOUNGE,
    MENS_CLOTHING,
    MENS_SHOES,
    MENS_UNDERWEAR_AND_SLEEPWEAR,
    SPORTS_AND_OUTDOORS,
    JEWELRY_AND_ACCESSORIES,
    BEAUTY_AND_HEALTH,
    TOYS_AND_GAMES,
    AUTOMOTIVE,
    ELECTRONICS,
    BOOKS,
    KIDS_FASHION,
    KIDS_SHOES,
    OFFICE_AND_SCHOOL_SUPPLIES,
    MUSICAL_INSTRUMENTS,
    PET_SUPPLIES,
}
